### ISSUE TITLE
select not working

### ISSUE THREAD

**Issue by xpajaro** [arctelix/drag-resize-snap#3]
I haven't tested this with other html elements but selects are definitely not working once DRS is plugged in. You can easily test this on you demo page.

To recreate the exact bug, I put the select outside the the draggable div.

**Comment by arctelix** [comment]
Are you attaching DRS to the <select> Element?  Try wraping it in a div.

If that does not work. Allow propagation on the mouse and touch events.

I will look into this as soon as time permits.  I believe removing e.stopPropagation() from the event handlers should do the trick.

**Comment by arctelix** [comment]
This has been fixed in 862f97e. Removed preventDefault onDown...  Evryting should work as expected now.
